{{ if .Values.apps.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: tools
  source:
    chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.2.0
    helm:
      releaseName: alloy
      valuesObject:
        alloy:
          configMap:
            content: |
              otelcol.receiver.otlp "otel_receiver" {
                http {}
                grpc {}

                output {
                  metrics = [otelcol.exporter.otlp.otel_metrics_exporter.input]
                }
              }
              
              otelcol.exporter.otlp "otel_metrics_exporter" {
                client {
                  endpoint = "http://lgtm-mimir-nginx/otlp"
                }
              }

              prometheus.remote_write "mimir" {
                endpoint {
                  url = "http://lgtm-mimir-distributor/api/v1/push"
                }
              }

              discovery.kubernetes "metrics_server" {
                role = "pod"

                selectors {
                  role = "pod"
                  label = "k8s-app=metrics-server"
                }

                namespaces {
                  names = ["kube-system"]
                }
              }

              prometheus.scrape "kubemetrics" {
                targets = discovery.kubernetes.metrics_server.targets
                forward_to = [prometheus.remote_write.mimir.receiver]
              }

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability

  info:
    - name: loki docs
      value: 'https://grafana.com/docs/alloy/latest/'
  
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
{{ end }}