{{ if .Values.apps.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-distributed
  namespace: argocd
spec:
  project: tools
  source:
    chart: lgtm-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.0.1
    helm:
      releaseName: lgtm
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability

  info:
    - name: loki docs
      value: 'https://grafana.com/docs/loki/latest/'
    - name: grafana docs
      value: 'https://grafana.com/docs/grafana/latest/'
    - name: tempo docs
      value: 'https://grafana.com/docs/tempo/latest/'
    - name: mimir docs
      value: 'https://grafana.com/docs/mimir/latest/'
  
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
{{ end }}