{{ if .Values.apps.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-distributed
  namespace: argocd
spec:
  project: tools
  source:
    chart: lgtm-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.0.1
    helm:
      releaseName: lgtm
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
{{ end }}