apiVersion: v2
name: toolset
description: A helm chart for bootstrapping a basic cluster tool infrastucture
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 6.8.0
    repository: https://argoproj.github.io/argo-helm
