argocd:
  global:
    domain: argocd.kombuese.app
    logging:
      format: json
      level: info
  configs:
    #cm:
    #  oidc.config: |
    #    name: ory
    #    issuer: https://auth.kombuese.app
    #    clientID: argocd
    params:
      otlp.address: ""
      server.insecure: true
      server.baseref: /
      server.rootpath: ""
    #rbac:
    #  policy.csv: |
    #gpg:
    #  keys:
    #repositories:
    #  kombuese:
    #    url: ssh://
    #    name: kombuese
    #    type: git
    #credentialTemplates:
    #  kombuese:
    #    url: ssh://
